# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GitHub_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GitHub_iOS
    pod 'ReactorKit'
    pod 'RxSwift', '6.5.0'
    pod 'RxCocoa'
    pod 'RxDataSources'
    pod 'Moya/RxSwift'
    pod 'SnapKit', '~> 5.6.0'
    pod 'Then'
    pod 'Kingfisher', '~> 7.2.0'

  target 'GitHub_iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GitHub_iOSUITests' do
    # Pods for testing
  end

end
